/*
 * This file is generated by jOOQ.
 */
package com.mdi.jooq.model;


import com.mdi.jooq.model.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in users
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>users.users</code>.
     */
    public static final Users USERS_ = com.mdi.jooq.model.tables.Users.USERS_;
}
